### ISSUE TITLE
[1.18] [Feature request] Actual skybox implementation

### ISSUE THREAD

**Issue by jamesjimmy88** [fishcute/Celestial#3]
It would be nice to have custom skyboxes like the ones you can have with Optifine.
It's possible to have them with vanilla shaders (if you need an example the [Dokucraft texture pack](https://dokucraft.co.uk/) has them, but for it to work you have to set your client's video settings to fancy, and doing that causes issues with several mods' rendering), so it might be doable.

**Comment by fishcute** [comment]
Technically, it's possible to make optifine-like skyboxes in the current version of Celestial, but I can probably implement something that will make it easier to do that.

**Comment by jamesjimmy88** [comment]
I tried using large image layers if that's what you mean, but the result was that the corners were way too noticeable.
What I'm asking for is something akin to the main menu panorama, where you have 6 images but the end result doesn't show any weird corners.
Also it would be super nice if the skybox object could have rotation and alpha parameters, so that you could use different skyboxes for the day and the night.

**Comment by fishcute** [comment]
Alright. Going to be attempting to implement this. If things go well, this will be in the next update.

**Comment by fishcute** [comment]
A better skybox system has been implemented in the 1.3 update.
