### ISSUE TITLE
[Suggestion] [1.18/1.19] Config to lower sky culling y-level

### ISSUE THREAD

**Issue by jamesjimmy88** [fishcute/Celestial#5]
If you get to y level 60 or below (or y level -60 for superflat worlds), the lower half of the sky gets culled:

Normal sky:
![2022-10-30_17 25 48](https://user-images.githubusercontent.com/58559532/198890024-c77bca39-7375-40b8-a20a-99616f81000b.png)

Below y level 60
![2022-10-30_17 25 44](https://user-images.githubusercontent.com/58559532/198890021-465e3a2e-7b35-40f1-b8b7-4a169d398f05.png)

It would be nice to have an option to disable it / edit the y-level this happens at.

**Comment by fishcute** [comment]
Don't think I've ever ran into something like this when testing. I'll have to see if there's anything I can do to fix this.

**Comment by fishcute** [comment]
You can now control this using the `void_culling_level` value in the `environment` section in the 1.3.2 update.
